image: $CI_REGISTRY/wma/continuous-integration/maven-build-image/maven-3-jdk-11

variables:
  # Use a maven repository nested in this repo to improve caching
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test

clean_build:
  stage: build
  script:
    - mvn clean package $MAVEN_CLI_OPTS -Dmaven.test.skip=true
  artifacts:
    paths:
      - target
  tags:
    - cloudformation-dev

unit_test_and_coverage:
  stage: test
  script:
    - 'mvn org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report $MAVEN_CLI_OPTS'
  artifacts:
    paths:
      - target
      # - target/surefire-reports
      # - target/site/jacoco
  tags:
    - cloudformation-dev
